#
# installation
#

- include: source.yml
  when: install_from == "source"

- include: binary.yml
  when: install_from == "packages"

#
# post installation configuration
#

# as documented in installation.rst
# workaround for https://github.com/Tendrl/ceph_integration/issues/57
- name: Specify log_cfg_path in tendrl.conf
  ini_file:
    dest=/etc/tendrl/tendrl.conf
    section=ceph_integration
    option=log_cfg_path
    value="/etc/tendrl/ceph_integration_logging.yaml"

- name: Start and enable tendrl-ceph-integration service
  service:
    name=tendrl-cephd
    state=started
    enabled=yes
