---
- name: Unconfigure firewalld on Tendrl server machine
  hosts: usm_server
  user: root
  vars:
    tendrl_uses_https: false
  tasks:

  - name: Disable port for Etcd
    firewalld:
      port=2379/tcp
      zone=public permanent=true state=disabled immediate=true
  
  - name: Disable port for Graphite
    firewalld:
      port=2003/tcp
      zone=public permanent=true state=disabled immediate=true
  
  - name: Disable port for GraphiteWeb
    firewalld:
      port=10080/tcp
      zone=public permanent=true state=disabled immediate=true
  
  - name: Disable port for Tendrl (with http)
    firewalld:
      service=http
      zone=public permanent=true state=disabled immediate=true
    when: not tendrl_uses_https
  
  - name: Disable port for Tendrl (with https)
    firewalld:
      service=https
      zone=public permanent=true state=disabled immediate=true
    when: tendrl_uses_https
  
  - name: Disable port for tendrl-api
    firewalld:
      port=9292/tcp
      zone=public permanent=true state=disabled immediate=true
 
  - name: Disable port for Grafana Server
    firewalld:
      port=3000/tcp
      zone=public permanent=true state=disabled immediate=true
 
  - name: Disable port for tendrl-monitoring-integration
    firewalld:
      port=8789/tcp
      zone=public permanent=true state=disabled immediate=true

- name: Unconfigure firewalld on Tendrl storage nodes
  hosts: usm_nodes
  user: root
  tasks:

  - name: Disable port for tendrl-gluster-integration
    firewalld:
      port=8697/tcp
      zone=public permanent=true state=disabled immediate=true
