
#
# Installation
#

- name: Directory for git repository
  file:
    path="{{ tendrl_frontend_repo }}"
    state=directory

- name: Clone git repository
  git:
    repo={{ tendrl_frontend_repo_url }}
    version={{ tendrl_frontend_repo_branch }}
    dest={{ tendrl_frontend_repo }}

- name: Install gulp
  npm:
    name=gulp
    global=yes
    path={{ tendrl_frontend_repo }}

- name: Install tendrl_frontend gulp packages
  npm:
    path={{ tendrl_frontend_repo }}

# As documented in Issue: https://github.com/Tendrl/tendrl_frontend/issues/78
- name: Install fontconfig dependency for gulp
  yum:
    name={{ item }}
    state=present
  with_items:
    - fontconfig
    
- name: Run gulp compile command
  command: gulp
    chdir={{ tendrl_frontend_repo }}

# As documented in documentation: https://github.com/Tendrl/tendrl_frontend/blob/master/docs/deployment.adoc
# Directory /var/www/tendrl/ is used because same directory is used by installation from packages
- name: Copy web files generated by gulp
  command: "cp -r {{ tendrl_frontend_repo }}/dist/ /var/www/tendrl/"
